name: Explore CI

# ───────── trigger rules ─────────
on:
  push:
    branches: [main, staging]
    tags:     ["v*"]
  pull_request:
    branches: [staging]

# ───────── shared constants ─────────
env:
  GODOT_VERSION: 4.4.1-stable           # one place to bump
  WEB_PRESET: "Web"                     # must match preset name
  IOS_PRESET: "iOS"
  GODOT_BASE: https://github.com/godotengine/godot/releases/download

jobs:
# ───────────────── WEB BUILD & PAGES DEPLOY ─────────────────
  web:
    runs-on: ubuntu-latest

    steps:
      # 1 ▸ checkout (with WizardCore submodule)
      - uses: actions/checkout@v4
        with: { submodules: recursive }

      # 2 ▸ cache headless binary + templates
      - name: Cache Godot
        id: godot-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/godot
            ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}
          key: godot-${{ runner.os }}-${{ env.GODOT_VERSION }}

      # 3 ▸ download only if cache missed
      - name: Install Godot headless + templates
        if: steps.godot-cache.outputs.cache-hit != 'true'
        run: |
          VERSION=${GODOT_VERSION}
          base=${GODOT_BASE}/${VERSION}

          # -- headless binary
          wget -q ${base}/godot-${VERSION}-linux-headless.64.zip -O godot.zip
          unzip -q godot.zip -d ~/godot
          chmod +x ~/godot/godot

          # -- export templates
          wget -q ${base}/godot-${VERSION}-export-templates.tpz -O templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/${VERSION}
          unzip -q templates.tpz -d ~/.local/share/godot/export_templates/${VERSION}

      # 4 ▸ export HTML5
      - name: Export HTML5
        run: |
          ~/godot/godot --headless \
            --export-release "${WEB_PRESET}" build/web/index.html

      # 5 ▸ save artifact (optional)
      - uses: actions/upload-artifact@v4
        with:
          name: html5-build
          path: build/web

      # 6 ▸ deploy to GitHub Pages (main & tags)
      - name: Deploy to Pages
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          keep_history: true

