name: Explore CI

# ──────────────── trigger rules ────────────────
on:
  push:
    branches: [main, staging]
    tags: ["v*"]
  pull_request:
    branches: [staging]

# ──────────────── shared variables ─────────────
env:
  GODOT_VERSION: "4.4.1"               # update in ONE place when bumping
  WEB_PRESET: "Web"                    # must match preset name in Godot
  IOS_PRESET: "iOS"

jobs:
# ──────────────────── Web build & deploy ────────────────────
  build-web:
    runs-on: ubuntu-latest

    steps:
    # 1 ▸ checkout repo + submodules (WizardCore)
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    # 2 ▸ cache Godot headless + export templates
    - name: Cache Godot ${{ env.GODOT_VERSION }}
      id: godot-cache
      uses: actions/cache@v4
      with:
        path: |
          ~/godot
          ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable
        key: godot-${{ runner.os }}-${{ env.GODOT_VERSION }}

    # 3 ▸ download only on cache miss
    - name: Install Godot headless + templates
      if: steps.godot-cache.outputs.cache-hit != 'true'
      run: |
        wget -q https://github.com/godotengine/godot/releases/download/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip -O godot.zip
        unzip -q godot.zip -d ~/godot
        chmod +x ~/godot/Godot_v${GODOT_VERSION}-stable_linux.x86_64
        wget -q https://github.com/godotengine/godot/releases/download/Godot_v${GODOT_VERSION}-stable_export_templates.tpz -O templates.tpz
        mkdir -p ~/.local/share/godot/export_templates
        unzip -q templates.tpz -d ~/.local/share/godot/export_templates

    # 4 ▸ export HTML5 build
    - name: Export HTML5
      run: |
        ~/godot/Godot_v${GODOT_VERSION}-stable_linux.x86_64 --headless \
          --export-release "${{ env.WEB_PRESET }}" build/web/index.html

    # 5 ▸ upload artifact for manual download
