name: Build • Windows

on:
  push:
    branches: [main]
    tags:     ["v*"]
  pull_request:
    branches: [main]

env:
  GODOT_VERSION:  "4.4.1-stable"          # keep in sync with build.yml
  GODOT_BASE_URL: "https://github.com/godotengine/godot/releases/download"
  WIN_PRESET:     "Windows Desktop"       # make sure this preset exists

jobs:
  build-windows:
    runs-on: ubuntu-latest                # Linux editor can export Win EXEs
    steps:
    # checkout
    - uses: actions/checkout@v4
      with: {submodules: recursive}

    # ───── Install prerequisites ─────
    - name: Install Wine + rcedit
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends wine64
        mkdir -p $HOME/tools
        wget -q https://github.com/electron/rcedit/releases/download/v1.1.1/rcedit-x64.exe \
             -O $HOME/tools/rcedit.exe
        # Tell Godot where to find it
        mkdir -p ~/.config/godot
        printf "[export]\nwindows/rcedit = \"%s\"\n" "$HOME/tools/rcedit.exe" \
            >> ~/.config/godot/editor_settings-4.tres


    # cache editor + templates
    - name: Cache Godot
      id: godot-cache
      uses: actions/cache@v4
      with:
        path: |
          ~/godot
          ~/.local/share/godot/export_templates
        key: godot-${{ runner.os }}-${{ env.GODOT_VERSION }}-v5

    # install editor + templates if cache missed
    - name: Install Godot desktop + templates
      if: steps.godot-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -e
        base="${GODOT_BASE_URL}/${GODOT_VERSION}"
        mkdir -p ~/godot
        wget -q ${base}/Godot_v${GODOT_VERSION}_linux.x86_64.zip -O godot.zip
        unzip -q godot.zip -d ~/godot
        chmod +x ~/godot/Godot_v${GODOT_VERSION}_linux.x86_64

        wget -q ${base}/Godot_v${GODOT_VERSION}_export_templates.tpz -O templates.tpz
        mkdir -p /tmp/tpl && unzip -q templates.tpz -d /tmp/tpl
        cp /tmp/tpl/templates/* ~/.local/share/godot/export_templates/${GODOT_VERSION//-/.}/

    # export Windows build (exe + pck)
    - name: Export Windows Desktop
      run: |
        mkdir -p build/windows
        ~/godot/Godot_v${GODOT_VERSION}_linux.x86_64 --headless \
          --export-release "${WIN_PRESET}" build/windows/Explore.exe

    # upload artifact for download
    - uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: build/windows
